#!/bin/sh
#
#This script is used to run acl test suites

#umask 077

mkdir -p /tmp/acl-ptest/test
cp test/test.* /tmp/acl-ptest/test
export EXPORT_PATH="/tmp/acl-ptest/test"

set +e
rm -rf test-suite.log
make test-suite.log
exitcode=$?
if [ $exitcode -ne 0 -a -e test-suite.log ]; then
    cat test-suite.log
fi
exit $exitcode
